### ISSUE TITLE
qcacld-2.0/CORE/HDD/src/wlan_hdd_tx_rx.c:1449:10: error: implicit declaration of function ‘cfg80211_is_gratuitous_arp_unsolicited_na’

### ISSUE THREAD

**Issue by ranusha14** [8devices/qcacld-2.0#3]
I was compiling the qcacld 2.0 for blue bean driver .but it is throwing the error 

/home/ubuntu/qcacld-2.0/CORE/HDD/src/wlan_hdd_tx_rx.c: In function ‘hdd_rx_packet_cbk’:
/home/ubuntu/qcacld-2.0/CORE/HDD/src/wlan_hdd_tx_rx.c:1449:10: error: implicit declaration of function ‘cfg80211_is_gratuitous_arp_unsolicited_na’ [-Werror=implicit-function-declaration]
          cfg80211_is_gratuitous_arp_unsolicited_na(skb)) ||
          ^
cc1: all warnings being treated as errors
make[2]: *** [/home/ubuntu/qcacld-2.0/CORE/HDD/src/wlan_hdd_tx_rx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/ubuntu/qcacld-2.0/CORE/HDD/src/wlan_hdd_wext.c: In function ‘__iw_get_char_setnone’:
/home/ubuntu/qcacld-2.0/CORE/HDD/src/wlan_hdd_wext.c:8418:1: error: the frame size of 1040 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
 }
 ^
cc1: all warnings being treated as errors
make[2]: *** [/home/arpithamc/qcacld-2.0/CORE/HDD/src/wlan_hdd_wext.o] Error 1
make[1]: *** [_module_/home/arpithamc/qcacld-2.0] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-4.4.0-146-generic'
make: *** [wlan-sdio] Error 2

please help me solving this issue.

**Comment by Nevinskas** [comment]
It seems that the kernel patches wasn't applied. 

Apply these patches to the kernel:
https://github.com/8devices/qcacld-2.0/tree/CNSS.LEA.NRT_3.0/patches/kernel

**Comment by ranusha14** [comment]
ubuntu@ubuntu:~$ uname -a
Linux relysys 4.4.0-146-generic #172~14.04.1-Ubuntu SMP Fri Apr 5 16:51:29 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux.

**Comment by Nevinskas** [comment]
Follow this guide:
https://github.com/8devices/qcacld-2.0/blob/caf-wlan/LNX.LEH.4.2.2.2/docs/Linux.md

**Comment by amrutajoshi13** [comment]
How to configure  Access point and station in qcacld driver.
I am using blue bean radio module.

**Comment by manojams** [comment]
> I was compiling the qcacld 2.0 for blue bean driver .but it is throwing the error
> 
> /home/ubuntu/qcacld-2.0/CORE/HDD/src/wlan_hdd_tx_rx.c: In function ‘hdd_rx_packet_cbk’: /home/ubuntu/qcacld-2.0/CORE/HDD/src/wlan_hdd_tx_rx.c:1449:10: error: implicit declaration of function ‘cfg80211_is_gratuitous_arp_unsolicited_na’ [-Werror=implicit-function-declaration] cfg80211_is_gratuitous_arp_unsolicited_na(skb)) || ^ cc1: all warnings being treated as errors make[2]: *** [/home/ubuntu/qcacld-2.0/CORE/HDD/src/wlan_hdd_tx_rx.o] Error 1 make[2]: *** Waiting for unfinished jobs.... /home/ubuntu/qcacld-2.0/CORE/HDD/src/wlan_hdd_wext.c: In function ‘__iw_get_char_setnone’: /home/ubuntu/qcacld-2.0/CORE/HDD/src/wlan_hdd_wext.c:8418:1: error: the frame size of 1040 bytes is larger than 1024 bytes [-Werror=frame-larger-than=] } ^ cc1: all warnings being treated as errors make[2]: *** [/home/arpithamc/qcacld-2.0/CORE/HDD/src/wlan_hdd_wext.o] Error 1 make[1]: *** [_module_/home/arpithamc/qcacld-2.0] Error 2 make[1]: Leaving directory `/usr/src/linux-headers-4.4.0-146-generic' make: *** [wlan-sdio] Error 2
> 
> please help me solving this issue.

had u solved this issue

**Comment by valinskas** [comment]
```
#ifndef cfg80211_is_gratuitous_arp_unsolicited_na
#define cfg80211_is_gratuitous_arp_unsolicited_na(skb) 0
#endif
``` 

We have done something like this. Which branch you are compiling from ?

**Comment by manojams** [comment]
v5.4

**Comment by manojams** [comment]
> ```
> #ifndef cfg80211_is_gratuitous_arp_unsolicited_na
> #define cfg80211_is_gratuitous_arp_unsolicited_na(skb) 0
> #endif
> ```
> 
> We have done something like this. Which branch you are compiling from ?

im trying with v5.4

**Comment by valinskas** [comment]
![image](https://user-images.githubusercontent.com/1107625/161248412-9aa760ac-f524-4f0c-bc75-95e9653f4301.png)

**Comment by valinskas** [comment]
you want linux-5.4.x/CNSS.LEA.NRT_3.0 or _3.1 branch instead.

**Comment by manojams** [comment]
> you want linux-5.4.x/CNSS.LEA.NRT_3.0 or _3.1 branch instead.
CNSS.LEA.NRT_3.0  , using this branch , i think i should use v4.4  ,4.9 , 4.11 kernel  .

**Comment by valinskas** [comment]
hmm, you wrote " im trying with v5.4 ", this is why i told  `linux-5.4.x/CNSS.LEA.NRT_3.0` branch (it is how it is named)

**Comment by manojams** [comment]
HI valinskas we interfaced the qca9377 module to our board , able to setup the wifi part . as per schematics i can see that bluetooth part is interfaced as uart port . can u guide or simple breif abou  how to load bluetooth for qca9377 .

**Comment by valinskas** [comment]
https://github.com/8devices/qcacld-2.0/blob/CNSS.LEA.NRT_3.0/docs/Fluoride.md

Also note this howto is for old 4.x kernel series, 8devices did not investigate what it would take to enable BT (bluetooth) on the latest linux kernels.

**Comment by manojams** [comment]
yes im testing on kernel 4.11, but it shows interface is with usb , but qca9377 is interfaced uart in our board and wifi as sdio, it seems our board have similarites with red bean board
