### ISSUE TITLE
how to cross compile qcacld with arm

### ISSUE THREAD

**Issue by ranusha14** [8devices/qcacld-2.0#5]
I need to cross compile qcacld2.0 blue bean driver for arm.
I tried with the below command but it is not working.
root@root:~$ ARCH=arm
root@root:~$ CROSS_COMPILER_PATH=/opt/poky/2.4.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
root@root:~$  KERNEL_SRC_PATH=/opt/poky/2.4.2/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/src/kernel/

root@root:~/qcacld-2.0$ ARCH=${ARCH} CROSS_COMPILE=${CROSS_COMPILER_PATH} KERNEL_SRC=${KERNEL_SRC_PATH} make -j4 wlan-usb
grep: //CORE/HDD/src/wlan_hdd_main.c: No such file or directory
make CONFIG_CLD_HL_USB_CORE=y -C /opt/poky/2.4.2/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/src/kernel/ M=/home/arpithamc/Anusha_workspace/qcacld_cross_compile/qcacld-2.0 modules WLAN_ROOT= CONFIG_QCA_WIFI_ISOC=0 CONFIG_QCA_WIFI_2_0=1 CONFIG_QCA_CLD_WLAN=m WLAN_OPEN_SOURCE=0 BUILD_DEBUG_VERSION=1 CONFIG_CFG80211=m CONFIG_LINUX_QCMBR=y SAP_AUTH_OFFLOAD=1 CONFIG_PER_VDEV_TX_DESC_POOL=1 CFLAGS_MODULE=-Wno-misleading-indentation   MODNAME=wlan-usb
make[1]: Entering directory `/opt/poky/2.4.2/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/src/kernel'
  CC [M]  /home/qcacld-2.0/CORE/BAP/src/bapApiData.o
  CC [M]  /home/qcacld-2.0/CORE/BAP/src/bapApiDebug.o
  CC [M]  /home/qcacld-2.0/CORE/BAP/src/bapApiExt.o
  CC [M]  /home/qcacld-2.0/CORE/BAP/src/bapApiHCBB.o
In file included from /home/qcacld-2.0/CORE/BAP/src/bapApiData.c:67:0:
/home/qcacld-2.0/CORE/BAP/src/vos_trace.h:46:11: fatal error: vos_types.h: No such file or directory
 #include  <vos_types.h>  // For VOS_MODULE_ID...
           ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/home/qcacld-2.0/CORE/BAP/src/bapApiData.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/qcacld-2.0/CORE/BAP/src/bapApiHCBB.c:66:0:
/home/qcacld-2.0/CORE/BAP/src/vos_trace.h:46:11: fatal error: vos_types.h: No such file or directory
 #include  <vos_types.h>  // For VOS_MODULE_ID...
           ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/home/qcacld-2.0/CORE/BAP/src/bapApiHCBB.o] Error 1
In file included from /home/qcacld-2.0/CORE/BAP/src/bapApiDebug.c:67:0:
/home/qcacld-2.0/CORE/BAP/src/vos_trace.h:46:11: fatal error: vos_types.h: No such file or directory
 #include  <vos_types.h>  // For VOS_MODULE_ID...
           ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/home/qcacld-2.0/CORE/BAP/src/bapApiDebug.o] Error 1
In file included from /home/qcacld-2.0/CORE/BAP/src/bapInternal.h:72:0,
                 from /home/qcacld-2.0/CORE/BAP/src/bapApiExt.h:74,
                 from /home/qcacld-2.0/CORE/BAP/src/bapApiExt.c:69:
/home/qcacld-2.0/CORE/BAP/src/vos_api.h:61:10: fatal error: vos_types.h: No such file or directory
 #include <vos_types.h>
          ^~~~~~~~~~~~~
compilation terminated.

**Comment by Nevinskas** [comment]
I assume by #6 that this is solved.

**Comment by ranusha14** [comment]
Yes it is solved
