### ISSUE TITLE
usb 2-1: Direct firmware load for athsetup.bin failed with error -2 qcacld driver 2.0

### ISSUE THREAD

**Issue by ranusha14** [8devices/qcacld-2.0#6]
I have cross compiled qcacld driver and obtained wlan-usb.ko file but when i load the driver in device, i am getting error.
The driver is ported using yocto build.
errors : 
     1)        ol_transfer_bin_file: Loading setup file athsetup.bin
            usb 2-1: Direct firmware load for athsetup.bin failed with error -2
            ol_transfer_bin_file: Failed to get athsetup.bin
     2)    wlan: [1887:E :HDD] hdd_hostapd_SAPEventCB: 1228: ERROR: HDD Failed to find sta id!!

root@rt-falcon:~# wlan_usb: loading driver v4.5.20.037

ol_transfer_bin_file: Loading setup file athsetup.bin
usb 2-1: Direct firmware load for athsetup.bin failed with error -2
ol_transfer_bin_file: Failed to get athsetup.bin
wlan: [1884:E :VOS] ol_transfer_bin_file: transferring file: athwlan.bin size 591880 bytes done!
+HTCCreate ..  HIF :e9e1e400 
-HTCCreate (0xef1a9800) 
WDA_open-4688: WMA --> wmi_unified_attach - success
ol_if_dfs_attach: called; ptr=e9e6da9c, radar_info=e9e8da6c
wlan: [1884:E :SAP] dfs_init_radar_filters[201]: Unknown dfs domain 0 
+HWT
Target Ready! : transmit resources : 3 size:1792, MaxMsgsPerHTCBundle = 8
HTC Service Index : 1 TX : 0x100 : alloc:3 
HTC Service:0x0001, ULpipe:0 DLpipe:5 id:0 Ready
-HWT
is_full_reorder_offloaded? 0
HTC Service TX : 0x300 : allocation is zero! 
HTC Service:0x0300, ULpipe:1 DLpipe:5 id:1 Ready
HTC Service:0x0300 ep:1 TX flow control disabled
HTC Service TX : 0x301 : allocation is zero! 
 Target failed service 0x301 connect request (status:1)
TX HTT OFF, ep -1 size 0
htt_tx_attach:htt_desc_start:0xe8a40000 htt_desc_end:0xe8a5c200
HTC Service:0x0100, ULpipe:0 DLpipe:5 id:2 Ready
HTC Service:0x0100 ep:2 TX flow control disabled
wma_pre_start-5056: WMA --> wmi_unified_connect_htc_service - success
wma_mc_process_msg-21967: McThread: WNI_CFG_DNLD_REQ
HTC will not use TX credit flow control
__wmi_control_rx: WMI UNIFIED SERVICE READY event
wma_rx_service_ready_event-24799: WMA <-- WMI_SERVICE_READY_EVENTID
wlan: [54:E :WDA] wma_rx_service_ready_event: Firmware build version : 00000029
wlan: [54:E :WDA] wma_rx_service_ready_event: Board version: 0.21014003

wlan: [1887:E :SME] No Pending command waiting
wlan: [1887:E :HDD] hdd_hostapd_SAPEventCB: 1228: ERROR: HDD Failed to find sta id!!
wlan: [1887:E :PE ] __limProcessSmeDisassocCnf: 2899: received DISASSOC_CNF for a STA that does not have context, addr= 30:10:b3:5f:2f:07
TXRX: Deleting peer e9ed3000 (30:10:b3:5f:2f:07)
wlan: [1887:E :PE ] limProcessAssocReqFrame: 661: RSN enabled auth, Re/Assoc req from STA: 30:10:b3:5f:2f:07

**Comment by terrycmchan** [comment]
Hi ranusha14,

Have you fixed this issue?
I am also facing this problem.
Would you mind give me some suggestions?

Thanks!

**Comment by Nevinskas** [comment]
1) athsetup.bin file is not necessary. It should work without it.

2) Could you provide full log of commands after the error:
```
dmesg
ps aux
```

**Comment by ranusha14** [comment]
Hi terrycmchan,
       Download the athsetup.bin file from the below given link and compile [it.](https://github.com/hcyllw/QCA937x-for-OpenWrt/tree/master/qca937x/firmware).

**Comment by ranusha14** [comment]
Hi Nevinskas,
                     yes it works fine even without athsetup.bin file but still i saw the error in dmesg so i thought to solve it .
