### ISSUE TITLE
errors while loading qcacld driver in RZG1E  

### ISSUE THREAD

**Issue by ranusha14** [8devices/qcacld-2.0#7]
I have cross compiled qcacld 2.0 driver and loaded into RZG1E board .i am able to configure wifi but when wlan becomes ready there is an log error in dmesg .

how to remove this error - TXRX: ol_tx_classify: remove the peer reference e8a7a000.

root@rt-falcon:~# wlan_usb: loading driver v4.5.20.037
hif_usb_probe
Enter:hif_usb_disable_lpm,Line:127
hif_usb_disable_lpm: LPM isn't enabled
Exit:hif_usb_disable_lpm,Line:154
BCDDevice : 300
RX Bulk Ep:0x81 maxpktsz:512
athusb: alloc resources lpipe:4 hpipe:0xC0408280 urbs:32
RX Bulk Ep:0x82 maxpktsz:512
athusb: alloc resources lpipe:5 hpipe:0xC0410280 urbs:32
RX Bulk Ep:0x83 maxpktsz:512
athusb: alloc resources lpipe:6 hpipe:0xC0418280 urbs:32
RX Bulk Ep:0x84 maxpktsz:512
athusb: alloc resources lpipe:7 hpipe:0xC0420280 urbs:32
TX Bulk Ep:0x01 maxpktsz:512
athusb: alloc resources lpipe:0 hpipe:0xC0008200 urbs:32
TX Bulk Ep:0x02 maxpktsz:512
athusb: alloc resources lpipe:1 hpipe:0xC0010200 urbs:32
TX Bulk Ep:0x03 maxpktsz:512
athusb: alloc resources lpipe:2 hpipe:0xC0018200 urbs:32
TX Bulk Ep:0x04 maxpktsz:512
athusb: alloc resources lpipe:3 hpipe:0xC0020200 urbs:32
/proc/cld/athdiagpfs created
wlan: [1884:E :HDD] wlan_hdd_cfg80211_init: wiphy->bands[i] is NULL, i = 2
NUM_DEV=1 FWMODE=0x2 FWSUBMODE=0x0 FWBR_BUF 0
IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
wlan: [1887:E :HDD] MODE 1, CH 6, LWM 0, HWM 0, TXQDEP 1500
wlan: [1887:E :HDD] wlan(0) 00:00:00:00:00:00 Standalone
wlan: [1887:E :HDD] AP(6) c4:93:00:0f:bd:13
wlan: [1887:E :SME] No Pending command waiting
TXRX: ol_tx_classify: remove the peer reference e8a7a000
wma_set_bsskey-13518: BSS Key setup with vdev_mac c4:93:00:0f:bd:13

wlan: [1887:E :SME] No Pending command waiting
TXRX: ol_txrx_peer_find_add_id: Delete Peer e8a7a000
TXRX: Couldn't find peer from ID 29 - skipping security inits
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
wlan: [1399:E :HDD] hdd_hostapd_ioctl: 389: ifr or ifr->ifr_data is NULL
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000 
root@rt-falcon:~# wlan: [1399:E :HDD] hdd_hostapd_ioctl: 389: ifr or ifr->ifr_data is NULL
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000
TXRX: ol_tx_classify: remove the peer reference e8a7a000

**Comment by Nevinskas** [comment]
Could you also provide the full `dmesg` and `ps aux` command output, when the problem is reproduced?
