### ISSUE TITLE
Configuration of compilation for BIG ENDIAN platform

### ISSUE THREAD

**Issue by terrycmchan** [8devices/qcacld-2.0#8]
Hi,

I would like to know what is the settings of the compilation for BIG ENDIAN platform.
I set:
CONFIG_LITTLE_ENDIAN := 0
ANI_BIG_BYTE_ENDIAN

**Comment by Nevinskas** [comment]
It is defined in the same Kbuild file. Line 1358:
```
#Endianess selection
ifeq ($(CONFIG_LITTLE_ENDIAN), 1)
AH_LITTLE_ENDIAN=1234
CDEFINES += -DAH_BYTE_ORDER=$(AH_LITTLE_ENDIAN)
else
AH_BIG_ENDIAN=4321
CDEFINES += -DAH_BYTE_ORDER=$(AH_BIG_ENDIAN)
CDEFINES += -DBIG_ENDIAN_HOST
endif
```

Does this answer your question?
