### ISSUE TITLE
Compile qcacld driver for Dragonboard 410c

### ISSUE THREAD

**Issue by danawaz** [8devices/qcacld-2.0#9]
Hi, is it possible to compile the qcacld with dragonboard 401c? Has anyone tried this before? For Rpi it says the kernel version is 4.11. Do I need the same kernel version on linaro on dragonboard 401c to make it work? I have a dragonboard 410c with a kernel version of 4.14.

**Comment by Nevinskas** [comment]
The branch caf-wlan/LNX.LEH.4.2.2.2 version is updated to work on newer kernel 4.15. I think it should also work on 4.14 version:
https://github.com/8devices/qcacld-2.0/commits/caf-wlan/LNX.LEH.4.2.2.2

You can try to use this branch.
